// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfxeqlhxaabzzzgcgewl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmeGVxbGh4YWFienp6Z2NnZXdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3Mzg4NTIsImV4cCI6MjA1ODMxNDg1Mn0._N2knao0dsRrB0M6BP1c4h3bOblgi5PMd3hxlsO9AOc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);